### PR TITLE
add Travis-CI, coveralls.io, and fury.io badges

### PR DESCRIPTION
**Pull request by zmughal**
And various other clean ups:

- Update `README` using `pod2markdown`.
- Add `.gitignore`.
- Add `.travis.yml`to run tests on Travis-CI and send report to coveralls.io.

### CODE REVIEW

**Comment by garu** [comment]
Brilliant! Thanks! \o/

**Comment by garu** [comment]
just shipped version 0.38 to CPAN with your contribution! Thanks again! If you see anything else you can help with, you know how to find me ;)

Cheers!

**Comment by zmughal** [comment]
Excellent! I'm planning to put in some more PRs and blogging too!

**Comment by garu** [comment]
:+1:

**Comment by neilbowers** [comment]
:+1:

**Pull request merged**
